apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-run-
spec:
  params:
  - name: GIT_USER_NAME
    value: pipline
  - name: GIT_USER_EMAIL
    value: pipeline@localhost
  - name: GIT_CODE_REPO
    value: git@github.com:ibm-cloud-automation/hello
  - name: GIT_CODE_REVISION
    value: main
  - name: GIT_CONFIG_REPO
    value: git@github.com:ibm-cloud-automation/hello-config
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc:5000/demo/hello
  pipelineRef:
    name: hello
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: pipeline-source-pvc
  - name: github-credentials
    secret:
      secretName: github
