---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hello-app
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: hello-trigger
---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: hello-trigger
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: hello-app
  template:
    ref: hello-app
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: hello-app
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.head_commit.id)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: hello-app
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: main
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: hello-run-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: hello
      params:
      - name: GIT_CODE_REPO
        value: $(tt.params.git-repo-url)
      - name: GIT_CODE_REVISION
        value: $(tt.params.git-revision)
      - name: GIT_USER_NAME
        value: pipeline
      - name: GIT_USER_EMAIL
        value: pipeline@localhost
      - name: IMAGE_NAME
        value: image-registry.openshift-image-registry.svc:5000/demo/hello
      - name: GIT_CONFIG_REPO
        value: git@github.com:ibm-cloud-automation/hello-config
      workspaces:
      - name: source
        persistentVolumeClaim:
          claimName: pipeline-source-pvc
